### ISSUE TITLE
Can't access farm management page on a fresh install of a hosted 3bot

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1043]
Created a new threebot connect account, deployed a hosted 3bot with the deployer.
used deployer: production: https://deploy3bot.grid.tf/

Can't access farm mangement page because of:

Not logged in with 3Bot or in dev mode.

Seems like I don't have any threebot id coming back from `/auth/authenticated`:
```
{"username": "nele.3bot", "email": "dylan_verstraete1@hotmail.com", "tid": null, "devmode": false}
```

But my identity is present on testnet? http://explorer.testnet.grid.tf/explorer/users/824

![Screenshot from 2020-09-07 15-43-06](https://user-images.githubusercontent.com/17138347/92393867-d8658200-f120-11ea-976b-406254c6ff5c.png)

I think it's looking up the wrong identity, it looking for `nele.3bot` whilst it should be looking for `nele_nele@threefold.me`

**Comment by zaibon** [comment]
So let me 1st recap the issue here.

When an hosted 3bot is deployed, 2 new identities are generated for it, 1 for mainnet, 1 for testnet and the user that requested the deployment is added as admin.

While this allow the user that requested the deployment to use this 3Bot. Any action made from this 3Bot is actually done from the new generated identities. Not the identity of the user that created it in the first place (the identity that is linked to its 3bot connect app)

So this a multiple problem I think:
- a user has no way to actually do action on the grid as himeself. it's always through a random identity that he somehow has right to use.
- this setup means any admin of this threebot can do action on the grid using an identity that is in no way link to him
- There is no way for an existing user to deployed an Hosted 3Bot and use it's already existing identity for it.
- The last point makes the farm management app useless since it only allow you to manage farm own by the 3Bot itself.

**Comment by xmonader** [comment]
> There is no way for an existing user to deployed an Hosted 3Bot and use it's already existing identity for it.

To clear that, you can create a 3bot online and add your 3bot connect words to it

**Comment by despiegk** [comment]
indeed we cannot ask from people to use their 3bot connect words on something which is hosted on the grid !

this is super dangerous and people would grill us for it very fast 
so what we have now is not ideal but at least there is something

we need to rethink: DID, private key storage, which keys on 3bot, ...

**Comment by zaibon** [comment]
> indeed we cannot ask from people to use their 3bot connect words on something which is hosted on the grid !

This was the original design BTW, so indeed this need to be rethink sooner then later.

>  so what we have now is not ideal but at least there is something

There is no solution that doesn't involve loading your 3bot connect words in your 3Bot. What @xmonader says is that you can load your existing identity to the Hosted 3bot once it's live. This still means the 3bot connect keypair will be on the 3bot.

**Comment by despiegk** [comment]
we cannot do that, its that simple, DO NOT push anyone to copy their words to their 3bot on grid, we cannot do this !!!
we can only do what we do today, a new identity and then we make us admin to it

**Comment by zaibon** [comment]
So this issue stays open. We don't have a solution for farmer with existing identities to use hosted 3bot.

**Comment by DylanVerstraete** [comment]
Also the hosted threebot has issues for a new user. If you make a fresh account in the threebot connect app and after that you try to run a hosted threebot you cannot even manage your farms.. This is because this threebot connect account is not registered on the grid itself.

**Comment by DylanVerstraete** [comment]
This is the farm management page you will see if you run a fresh hosted threebot that comes from a fresh threebot connect account.
![photo_2020-09-07_15-17-23](https://user-images.githubusercontent.com/17138347/92485230-f7304b00-f1ea-11ea-85ad-21349db20ac0.jpg)

**Comment by zaibon** [comment]
Documentation how to migrate a farm on an hosted 3bot has been created: https://manual2.threefold.io/#/farm_migration
