### ISSUE TITLE
script s3 deployment end 2 end

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1107]
script s3 deploymennnt end 2 end

- wallet named `wallet`
- consult the manual code for provisioning  https://manual2.threefold.io/#/code_storage

**Comment by OmarElawady** [comment]
The script now does the following steps, after each step it's described what is done and what is expected then waits for the user to check actually that all went well and waits for an enter to resume:

1. Deploys MinIO master/slave setup with 7/3 data/parity ratio.
2. Remove 3 random ZDB storages.
3. Remove the master.
4. Remove the slave and redeploying a new master/slave with newly created 3 ZDBs instead of the dead ones.

This is the Prothemeus that monitors the disks:
![Screenshot from 2020-09-15 13-43-15](https://user-images.githubusercontent.com/13040543/93206334-84c6ea00-f759-11ea-9863-22ab020ff0ec.png)
![Screenshot from 2020-09-15 13-42-43](https://user-images.githubusercontent.com/13040543/93206337-855f8080-f759-11ea-9929-931f2474baaf.png)

1. Both master/slave up with 10 disks.
2. Both master/slave up with 7 disks.
3. Master down, slave with 7 disks.
4. Master/Slave down, then new master/slave up with 10* disks.

_* There's a (bug?) in reporting the number of total disks by (MinIO?). It shows that only 7 are up but manually investigating the container and the server behavior, it should report 10._


The  manual checks done in between:
1. After the first step, use restic to make backup/restore and s3fs to mount the master partition:
![Screenshot from 2020-09-15 13-51-32](https://user-images.githubusercontent.com/13040543/93207191-e3409800-f75a-11ea-9e9d-3c4b62721e89.png)

2. After the second step master is still accessible but in read-only mode. 
![Screenshot from 2020-09-15 13-52-09](https://user-images.githubusercontent.com/13040543/93207213-ee93c380-f75a-11ea-9c27-d4700f40a814.png)

3. After the third step, slave is mountable in read-only mode.
![Screenshot from 2020-09-15 13-52-49](https://user-images.githubusercontent.com/13040543/93207228-f3f10e00-f75a-11ea-9d9a-c8772c0093bb.png)

4. After the fourth step, every thing work as after 1.
![Screenshot from 2020-09-15 13-53-37](https://user-images.githubusercontent.com/13040543/93207245-f94e5880-f75a-11ea-926c-481883e271d7.png)

**Comment by Pishoy** [comment]
verified as above steps:

this is step 2
```
root@tfwallet-prod:~/codescalers/test3# echo fietestsr >> /tmp/file3
root@tfwallet-prod:~/codescalers/test3# cat /tmp/file3
fietestsr

root@tfwallet-prod:~/codescalers/test3# mv /tmp/file3 .
mv: failed to close './file3': Input/output error
```
- step 4
```
root@tfwallet-prod:~/codescalers/test3# mv /tmp/file3 .
root@tfwallet-prod:~/codescalers/test3# ls
file3  myfile.txt  newfie  nginxtest.pid
root@tfwallet-prod:~/codescalers/test3# cat file3 
fietestsr

```

-sdk version
```
root@tfwallet-prod:/opt/js-sdk# git log -1
commit ba19309983fdb79724e4969284d97e2659e27b6a (HEAD -> development_minio_zdb_wait, origin/development_minio_zdb_wait)
Author: Omar Elawady <omarelawady1998@gmail.com>
Date:   Thu Sep 17 15:28:38 2020 +0200

    Wait for namespaces to be deployed

```
