### ISSUE TITLE
pool needs additional capacity to support this workload

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1128]
While deploying a demo app I got this error while even I'm not paying anything

```
(StopChatFlow(...), 'failed to deploy workload on node 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib due to error 402 Client Error: pool needs additional capacity to support this workload for url: https://explorer.testnet.grid.tf/api/v1/reservations/workloads')
```

**Comment by OmarElawady** [comment]
The error message "failed to deploy workload on node 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib due to error" is only present in the [`dry_run`](https://github.com/threefoldtech/js-sdk/blob/9dfa6a3a1b507ff4703ef348ea3d9956a02a1fcf/jumpscale/sals/reservation_chatflow/deployer.py#L196) method. Which means that a workload in `network.network_resources` failed to deploy to the error mentioned after it. This error is raised from [here](https://github.com/threefoldtech/tfexplorer/blob/b42b3d16c7f6a89bc7964e356b3ea15a230bca1e/pkg/workloads/reservation.go#L156), it indicates that the pool doesn't have enough resources to deploy this workload for at least two minutes. But AFAIK network workloads doesn't incur any cost, so even an empty pool shouldn't fail because of lack of resources. So can `network.network_resources` contain workloads of types other than adding a node (or access) to a network? And if no, how the pool requirements for such workloads are calculated?

**Comment by OmarElawady** [comment]
The failing workload: [478649](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/478649).

**Comment by OmarElawady** [comment]
I tried to add a new network on a newly created empty pool and it didn't fail! And it's shown in the "Deployed workloads" [479183](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/479183).

code:
```python
network = j.sals.zos.network.create('10.10.0.0/16', 'test_net_cap152')
j.sals.zos.network.add_node(network, '72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib', "10.10.1.0/24", 1883)
wg_quick = j.sals.zos.network.add_access(network, '72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib', "10.10.2.0/24", ipv4=True)
result = []
for resource in network.network_resources:
    result.append(j.sals.zos.workloads.deploy(resource))
```
