### ISSUE TITLE
The email is always gone in farm settings in a new 3bot instance

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1151]
![ff](https://user-images.githubusercontent.com/21218053/93080984-ce96ce00-f68e-11ea-9b7e-b3bb35471d08.png)

**Comment by xmonader** [comment]
seems the problem is coming from this https://github.com/threefoldtech/js-sdk/blob/1cdd72122e044799c18e017fe2365dae7dad6738/jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js#L10

it executes the request directly to the explorer without authentication, should go to farmmgmt actor and that actor send the request to the explorer and sign it
