### ISSUE TITLE
notification system for the dashboard 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1335]
allow dashboard to have notifications 

more to be spec'd

**Comment by AhmedSa-mir** [comment]
Current status:
- Added `notification queue` tool to be used by services to push notifications to the admin dashboard. Used redis lists to save  notifications to be consumed periodically by the frontend. Notification are not persistent that is the user get notified in the UI and these notifications are not saved anywhere. If a service needs to keep an important notification in history it should raise an alert as well.
- Added `service manager` running as a server in the threebot rack. This server manages the background services being added to the threebot instance. One can define his own service to run in the background by overriding the `job method` to be run. Currerntly the service manager is not finished yet. We have some problems on stopping the background services because of gevent kill methods misbehaviour (and also tried [gevent-tasks](https://pypi.org/project/gevent-tasks/) package but has also problem with stopping tasks)

**Comment by AhmedSa-mir** [comment]
#### Update:
- Removed dependency of our service manager on `gevent-tasks` because of errors occuring during stopping greenlets that are scheduled but are not currently running. But implemented our service manager using the methodology used in `gevent tasks` (gevent.spawn_later() + greenlet.link(callback)) instead of gevent spawn and kill which had unexpected behaviour.
- Added actors for notifications to fetch notifiacations from our `notification queue` and some changes in the UI but UI still not yet finished.
- Tested stellar background service and working fine.

#### TODO:
- Finish rendering notifications in UI.
- Code review
- More testing with different background services.

**Comment by dmahmouali** [comment]
#### update:
- save a bit of notification history by caching the last 10 notifications in another list.
- enhance UI and added info, working, and error categories.
- added new background service: `DiskCheckService`.
- enhance code.

**Comment by mhost39** [comment]
branch: development
commit: 08cd9c53e89577b648d31a0e8e90164d71e044c7
![image](https://user-images.githubusercontent.com/31102305/97173190-d327c980-1798-11eb-8779-caa31d249298.png)
