### ISSUE TITLE
when deploying 3bot be clear about the identity usage

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1416]
make sure to mention the following
- tell user identity created
- tell creation of capacity pool
- tell user we funded the capacity pool with X TFT
- tell user we created mgmt network and it succeeded
- tell user that the funding of the 3bot needs to happen < 1 h
- remember in local DB (if needed)
  - user identity (name,id)
  - capacity pool (name,id)
  - mgmt network (name,id)

**Comment by OmarElawady** [comment]
The linked PR now creates a new main and test identity. Then it uses the new main identity to create a pool and a network. The new 3Bot is deployed on the new pool and network.

Things that may need to be modified:
1. The new 3Bot doesn't get listed since it belongs to another identity.
2. The new identities along with their private keys are stored locally on the deployment site (j.core.identity.new_identity).
3. The pools don't get reused and the newly created pools don't get stored in the UserPool factory.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 092358e26dfb12dbe8395fd7da00a93cb90a8ec5, **Branch** Development

![ff6](https://user-images.githubusercontent.com/21218053/98553171-004f9e00-22a8-11eb-826d-41889d251ce4.png)
![ff5](https://user-images.githubusercontent.com/21218053/98553167-ffb70780-22a7-11eb-9425-663820da8139.png)
![ff4](https://user-images.githubusercontent.com/21218053/98553163-ff1e7100-22a7-11eb-971d-c6119fb6a602.png)
![ff3](https://user-images.githubusercontent.com/21218053/98553161-fe85da80-22a7-11eb-8ff5-af7e06655ef5.png)
![ff2](https://user-images.githubusercontent.com/21218053/98553160-fded4400-22a7-11eb-9312-7567891e7e1f.png)
![ff1](https://user-images.githubusercontent.com/21218053/98553158-fd54ad80-22a7-11eb-832b-dd846c8e6a3b.png)
![ff](https://user-images.githubusercontent.com/21218053/98553154-fc238080-22a7-11eb-9ec1-a450bca99941.png)
