### ISSUE TITLE
How are existing threebots updated?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1503]
### Description
After updating to the latest master code I could no longer start my default threebot: 
error starting threebot in a local installation #1502 

'backup' was added to the default packages After deleting the 'default' threebot, I could start it since it was recreated.
Is this only a problem with the default packages? 

### Version information
* OS: osx
* project commit/version: e.g. js-sdk 11.0-b9 ( current master branch)

**Comment by waleedhammam** [comment]
Seems like the setup was very old since it was early development phase and there were a lot of breaking changes by then, backup package was added almost 3 months ago or later


- Currently updating should be just `git pull ; poetry install # if lock file changes if not no need; threebot restart` gonna be enough

**Comment by robvanmieghem** [comment]
thanks @waleedhammam
