### ISSUE TITLE
peertube solution: impossible to video, request entity too large

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#1561]
I deployed a peertube instance from the markeplace. But when I tried to update a video to it, I always get this error:
![2020-10-29_612x1121_scrot](https://user-images.githubusercontent.com/303164/97579528-758eb980-19f2-11eb-8224-f6018f192c04.png)

**Comment by xmonader** [comment]
Probably client_max_body_size is misconfigured

**Comment by zaibon** [comment]
That's what I though too

**Comment by RafyAmgadBenjamin** [comment]
According to these articles:
- https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
- https://www.keycdn.com/support/413-request-entity-too-large#:~:text=A%20413%20Request%20Entity%20Too,processed%20by%20the%20web%20server.&text=An%20example%20request%2C%20that%20may,e.g.%20a%20large%20media%20file).

The error is related to  `client_max_body_size`

According to Nginx official docs 
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

we set `client_max_body_size` to zero to prevent this checking 
```Setting size to 0 disables checking of client request body size.```

we created a new image and tested it with interactive `True` and it worked 
the file size was 1.5 MB which exceeds the default value which is 1 MG 
![image](https://user-images.githubusercontent.com/46320202/98002843-b0c82880-1df6-11eb-9910-4616ea639fac.png)

but when interactive is `False`
we got this error `deleting container due to so many crashes`

**Comment by RafyAmgadBenjamin** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/46320202/98093050-1fa59000-1e90-11eb-9809-a3b86a7018aa.png)

**Comment by mhost39** [comment]
branch: development

![image](https://user-images.githubusercontent.com/31102305/98119558-6d80bf00-1eb5-11eb-9302-c9c62b83287b.png)
![image](https://user-images.githubusercontent.com/31102305/98119677-9c973080-1eb5-11eb-96d8-9ed6548bd528.png)
