### ISSUE TITLE
threebot start fails due to incompatible gevent ABI on fresh install

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1713]
Created a fresh install of js-sdk (as per the [instructions](https://threefoldtech.github.io/js-sdk/wiki/#/./quick_start?id=installation-for-experts-or-developers):

```
git clone git@github.com:threefoldtech/js-sdk
cd js-sdk
poetry install
```

then tried to start the threebot:

```
poetry shell
threebot start --local
```

it immediately crashes, with follwing stack trace:

```
Traceback (most recent call last):
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/bin/threebot", line 2, in <module>
    from jumpscale.entry_points.threebot import cli
  File "/home/lee/js-sdk/jumpscale/entry_points/threebot.py", line 1, in <module>
    from gevent import monkey
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/lee/.cache/pypoetry/virtualenvs/js-sdk-4phGcms2-py3.8/lib/python3.8/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 144 from PyObject
```

* OS: manjaro linux

note: a workaround to this problem seems to be to manually build `gevent` inside of the venv as such: `pip install -U --force-reinstall --no-binary :all: gevent`

**Comment by abom** [comment]
Yes, that's related to incompatible binary builds with older python platforms, see https://github.com/threefoldtech/js-ng/issues/458.

We still support python 3.6, while most people here use ubuntu, some supported versions still has older python distributions. So, we either upgrade gevent/greenlet to a newer release which does not has `manylinux1` binary builds and only has [manylinux2010](https://www.python.org/dev/peps/pep-0571/), or keep current versions as long as we support python 3.6.

But we will look again and check if things get sorted out in latest gevent/greenlet releases or we add required gevent development libraries to build gevent from source, because it's not available by default in all distributions.

**Comment by abom** [comment]
Should be resolved by #3003 (Tested on `manjero linux`)

**Comment by MElborolossy** [comment]
@LeeSmet Kindly verify that it is working after last updates

**Comment by xmonader** [comment]
@MElborolossy please verify on latest Ubuntu. That should be enough

**Comment by MElborolossy** [comment]
Verified
- Create a new venv using `poetry install`
- jsng version: 11.0b13
- gevent: 21.1.2
![image](https://user-images.githubusercontent.com/11272864/119027675-edc8c680-b9a6-11eb-9d22-d78c069d1cf8.png)

- Server Running
![image](https://user-images.githubusercontent.com/11272864/119027614-d8539c80-b9a6-11eb-9573-fc765e494b3d.png)
