### ISSUE TITLE
Add poetry build to the workflow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1786]
projects needs to always pip installable with correct dependencies, to make sure of that let's add poetry build to the workflow

**Comment by sameh-farouk** [comment]
there are many workflows, I assume you mean the js-sdk.yml one?

**Comment by sameh-farouk** [comment]
also since pip 19.0, it becomes possible to pip install a Poetry-managed Python package from a git repository without setup.py
ex: `pip install git+{git-repository-url}`
so I guess we only need the output of the `poetry build` command if we want to publish it `poetry publish` to an external repository (likely PyPi)?
