### ISSUE TITLE
Drop the 3bot import from another network functionality

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1793]
### Description
![Screenshot 2020-12-08 at 09 18 08](https://user-images.githubusercontent.com/3511318/101475213-66cde780-394c-11eb-8eb3-8c6493518c80.png)

Imho Testnet is testnet and not a staging environment

**Comment by xmonader** [comment]
every 3bot starts with 2 identities (main, test) registered on mainnet, testnet respectively, as requested. Scenario is:
if you used the testnet deployer to deploy a 3bot (two identities will be created based on the tname, solution name with the words derived from the password you defined), now if you go to the mainnet deployer and try to create one with the same combination (tname, password) it'll say it exists in the network and you should be importing instead of creating

**Comment by rkhamis** [comment]
what's the final consensus here? Indeed original spec goes against this feature request.

**Comment by xmonader** [comment]
@rkhamis We will create one identity with the 3bot based on the network it's getting created from
