### ISSUE TITLE
VDC: As a user I want the chat flow to clean failed solutions deployments if it failed

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2027]
### Description

we need to clean the failed deployed charts, some times the pods keep pending and the chat flow raises an error but afterward it didn't clean the failed deployments for this chart

**Comment by xmonader** [comment]
that's the case already @OmarElawady if true please move to verification

**Comment by OmarElawady** [comment]
Currently, it cleans up the charts that failed due to lack of resources. However, it doesn't clean it up if it failed for any other reason (bad configuration, network problems, ...).

**Comment by MElborolossy** [comment]
According to @OmarElawady  Comment
Verified

Steps:
- Deploy taiga chart
- Failed due to lack of resources
![image](https://user-images.githubusercontent.com/11272864/104564320-73341700-5653-11eb-9a90-0e5a4cec5c60.png)
- List all Workloads and confirmed that it is deleted
![image](https://user-images.githubusercontent.com/11272864/104564451-965ec680-5653-11eb-8d46-6ad66cd89a91.png)
