### ISSUE TITLE
"Funding difference" screeen was not progressing

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2195]
Overall deployment time takes long for a VDC (did not time but long).  Last screen was "Funding difference" and this stayed on for very long. I pressed "reload page" in the browser and then was returned to the vdc deployer landing page after login: https://vdc.testnet.grid.tf/vdc/#/

Pushing "List VDC's" show me that the VDC was deployed and operational.  So the "Funding difference" screen was not progressing.

**Comment by xmonader** [comment]
- The payments on stellar networks aren't guaranteed 100% from the first time, we keep retrying to pay, sometimes I didn't manage to pay for 10 times in a row

- There're multiple payments happening on the system 
  1. us creating and funding the user wallet
  2. paying the grid to provision the VDC for 1 hour (two times actually because we deploy on two pools)
  3. accepting money from the user into their prepaid wallet and transferring half of that to the provisioning wallet to fund the pools for 14 days
  4. recharging the cost of the 1 hour we paid upfront from the user prepaid wallet
  5. funding the difference due too the wrong pricing of the packages and we cover the loss
  
  It's completely dependant on how stellar network is doing.

**Comment by waleedhammam** [comment]
Verified, if it exceeded 5 mins it will raise an exception
