### ISSUE TITLE
3bot  on testnet stuck in loading on main Admin page

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2327]
The 3bot  on testnet is stuck on loading after successfully setting it up with the 3BOT Deployer , we tried multiple times and the result is same :

![image](https://user-images.githubusercontent.com/25789724/105680270-e87fd180-5f08-11eb-9dd6-914e2b3ac89c.png)

![image](https://user-images.githubusercontent.com/25789724/105680302-f46b9380-5f08-11eb-8676-af805f16f6a3.png)

**Comment by waleedhammam** [comment]
![image](https://user-images.githubusercontent.com/10658229/105683716-9df85800-5efc-11eb-97a8-ccfe8bcaba12.png)

![image](https://user-images.githubusercontent.com/10658229/105683749-a94b8380-5efc-11eb-88f9-d198815289c0.png)


Just deployed on testnet and deployed successfully, I think the problem is in your browser, can you try hard refresh, or using another browser or go incognito mode

**Comment by siddiquagig** [comment]
Worked successfully on another browser(Firefox) , indeed was a browser issue
