### ISSUE TITLE
use the explorer related to the identity in chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#250]
atm it seems Sukh registered on mainnet and this happened when trying to provision minio

![image](https://user-images.githubusercontent.com/64129/87576365-90525200-c6d1-11ea-977f-e316c5aca6db.png)

**Comment by waleedhammam** [comment]
Fix at: https://github.com/threefoldtech/js-sdk/pull/252

Default explorer should be taken from the identity itself, different than jsx. so that each identity instance has its own explorer
see:

![Screenshot from 2020-07-15 22-51-51](https://user-images.githubusercontent.com/10658229/87594789-c998bb00-c6ed-11ea-9689-ebf20c8a2395.png)


made this network reservation with it:
- https://explorer.grid.tf/explorer/reservations/10337

also when trying to deploy a container shows only mainnet wallets
![Screenshot from 2020-07-15 22-48-30](https://user-images.githubusercontent.com/10658229/87594547-6c9d0500-c6ed-11ea-8fb9-9fe033e9f1c2.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
