### ISSUE TITLE
Non-expired VDC not reachable

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2605]
I have a VDC with remaining TFTs and with expiry date > today + 1 month. But I can't reach it. 

![image](https://user-images.githubusercontent.com/30384423/108723439-8aa0d280-7524-11eb-8e03-b20b3dd3396b.png)

![image](https://user-images.githubusercontent.com/30384423/108723400-807ed400-7524-11eb-94fc-6a5c9c270465.png)

**Comment by gmachtel** [comment]
Was relaunched after restarting the trc. But root cause for website unavailable still unknown (needs to be found).

**Comment by scottyeager** [comment]
I am seeing the same thing on one of my VDCs. It's still available via kubectl, but can't reach the web frontend here: https://scott-veedeecee.vdctest.grid.tf/vdc_dashboard/

**Comment by OmarElawady** [comment]
> I am seeing the same thing on one of my VDCs. It's still available via kubectl, but can't reach the web frontend here: https://scott-veedeecee.vdctest.grid.tf/vdc_dashboard/

This is because the 3Bot is provisioned on the node "3bjMhue2QMYmnCcogLjUex3joXeFyf4fKBk5vroaWXme" which is down atm. The worker is hosted on the same node and this is also why it appears as "NotReady" in `kubectl get nodes`.

[workload](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/8139)

**Comment by scottyeager** [comment]
Thanks @OmarElawady, I'll just delete this VDC then.
