### ISSUE TITLE
Keep Presearch image in VDC aligned with the latest published Docker image

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2626]
Presearch intends to update regularly the Docker image. In a pure Docker setup it is recommended to have a Watchtower running to keep track of updates. 

In Kubernetes, rolling updates needs to be supported, to have the same effect.

**Comment by abdulgig** [comment]
@gmachtel , as discussed,  any new deployment will have the latest image from Presearch. You may verify and share feedback

**Comment by gmachtel** [comment]
Will check but I guess that we can only really be sure when a new image has been published by the Presearch team, to see whether it has been taken in. I will reach out to them.

**Comment by scottyeager** [comment]
Just to be clear, we're not just talking about new deployments. Presearch periodically publishes mandatory updates, and our solution should ideally handle these automatically.

In case this is helpful, here's what Trey from Presearch said about how their nodes handle updates:

> We have three mechanisms for forcing a node update remotely:
> 1) If the node is reachable, send a "shutdown" command, which will trigger the node to exit
> 2) If the node is reachable, send a "minimum version update", which will cause any nodes not already on the latest version to shutdown
> 3) If the node is unreachable, republish the latest version to docker hub. This will cause watchtower (if running) to pull down the image again and restart the node.
> 
> I do #3 periodically in cases like today, which restarts the node even if unreachable, since it's a pull vs. push mechanism.
> 
> The problem is the network can't reach a node to send it a command (like in the zombie node case), then it's just going to stay in that state indefinitely until something (like watchtower) restarts it.
> 
> That's why the zombie node issue is a big deal and we have to make sure to fix it permanently (working on it for this week).

For cases 1 and 2, I think that the "always" pull policy specified in the Helm chart should be sufficient. Case 3 is not something that Kubernetes apparently supports via any native mechanisms (see [here](https://stackoverflow.com/questions/59543373/auto-update-container-image-when-new-build-released-on-kubernetes), for example). Hopefully they do get the zombie node issue resolved to make case 3 irrelevant.

In the meantime, deleting the pod manually via kubectl would be one way to deal with zombie nodes. Deleting and redeploying through the marketplace is not ideal, as it creates a new node identity because it's volume doesn't persist between deployments.

**Comment by abdulgig** [comment]
@scottyeager, Presearch is already working on case 3 and they should be able to resolve it soon. It is beyond our scope as that "zombie" nodes exists within their system, not elsewhere. If the node becomes unreachable for whatever reason within a specified time range, it should be flushed out and the new one should be allowed to connect.

With Kubernetes' immutable infrastructure approach, all configuration is set at deployment time. So if there is an update, it will come through the published image by Presearch and automatically reflected in a redeployment or a new deployment. This is already working as Presearch published a new image last night and it is reflected.

As for node identity, it also binds to the user's registration code , right? I can see all nodes under my Presearch account. If there is any benefit/reward from a specific node, it is eventually going to reflect to the user's account, right ?

The node uses a public/private keypair to track identity. If that is allowed as a configurable option under presearch, perhaps we can preserve the node identity too. I will check with Trey

**Comment by scottyeager** [comment]
Zombie nodes are running but not connected to the Presearch network; it's an issue within the node. You might be thinking of "duplicate nodes", which show up as an existing connection from a node that is not in fact connected. I see that Trey will be prioritizing both of these issues soon, but in the meantime some solution for zombie nodes is necessary if this is going to be a functioning solution. I agree that unresponsive nodes should be flushed out, which is why I'm wondering if there's another solution besides manual intervention via kubectl.

Redeployment or a new deployment from our marketplace should not be necessary for node version updates. I see now that this is a bit more complicated, because our solution relies on a modified container which I'm presuming needs to be manually updated every time Presearch pushes an update. So I guess this is probably what's happening right now with non zombie nodes:

1. Presearch pushes updated image and triggers nodes to shutdown
2. Kubernetes sees the pod died and creates a new pod based on the latest image at `arrajput/presearch` which is now a version behind
3. We update our image, pods keep running and do not update

I can't verify this, because the node I deployed on a VDC apparently went zombie (I've never seen this in my experiments using flists), and stopped producing output. When I killed the container by killing the `presearch-node` process, Kubernetes deployed a new container based on the latest version. The new pod generated a new key pair, which is not what I was expecting.

It's true that each key pair does get associated with the user's registration code, but it is important to provide persistence for the keys. The first reason is that staking is done on a node identity basis, so users would have to move their stake each time new keys are generated. The perhaps bigger reason is that nodes accumulate a reliability score which is also associated with the key pair identity. I was surprised that my new pod generated new keys, as it appears we do have a persistent volume attached. Upon inspection, it seems that the volume gets mounted in the wrong place in the container (currently `/presearch`, should be '/app/node`).

**Comment by abdulgig** [comment]
@scottyeager, so 2 things,

1. You killed the pod and you got the latest version deployed which verifies our main goal here.
2. We will verify the mount path for keys today and then we can test together

**Comment by scottyeager** [comment]
Our goal is to ensure that nodes update automatically. We've only verified that a node can update with manual intervention. After a bit more testing, I think we're actually okay for cases 1 & 2 mentioned by Trey. It looks like newer node images exit automatically on startup if there's a mandatory update, whereas older ones did not.

The fact is still that my node did not update automatically because the node process stopped without exiting. Even if the current zombie issue is resolved, we still should be prepared for the odd case where a node gets stuck like this. Marketplace users aren't expected to necessarily have kubectl. I'd propose three ideas:

1. Put a kill switch on the web gateway for node operators to restart their pod (as opposed to redeploying, so node identity is retained)
2. Periodically reset the pods, ideally inspecting output logs to ensure a search isn't currently being served
3. When Presearch releases their node api, periodically check if PS sees the node and restart the pod if node app is running but not connected

For the mount path, verify against the Docker command documented here: https://nodes.presearch.org/instructions
Let me know when that is corrected and I'll be happy to test.

**Comment by abdulgig** [comment]
@scottyeager,  Great to have a discussion directly on this, so here is what we can do,

1. A restart button on the status page 
2. Fix the key mounts
3. When presearch rolls out their API, we can use it for any additional info / connectivity checks

We'll let you know when to test again

**Comment by abdulgig** [comment]
Please close if https://github.com/threefoldtech/js-sdk/issues/2642 is verified

**Comment by gmachtel** [comment]
Verified, works fine 👍 . Wiki updated.
