### ISSUE TITLE
harden $LANG check in 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2899]
related to https://github.com/threefoldtech/js-sdk/issues/496

**Comment by RafyAmgadBenjamin** [comment]
I have missed with my $LANG env. variable to be able to reproduce the issue 
``` bash
echo $LANG
threebot start --local
```

I got  this 
![image](https://user-images.githubusercontent.com/46320202/127147697-0938f0da-53f2-48a0-aea0-3fdbaa032e3a.png)

from what I see it is already hardened with a clear error message 

so are we okay with that @xmonader? or do you want another thing, if so please specify it to be able to work on it

**Comment by RafyAmgadBenjamin** [comment]
I have searched on how to solve this and be able to harden this error thrown by Click library but all the solutions, I have found that we have to export this env. variable before the python3 script run as python3 use locale setting
as mention here
https://stackoverflow.com/questions/39206705/python-3-throws-unicodeencodeerror-with-environment-variable-lang-c
https://stackoverflow.com/questions/47572800/setting-up-the-appropriate-character-encoding-for-a-pipenv-project-in-the-pychar
https://stackoverflow.com/questions/62054143/readthedocs-local-install-runtimeerror-click-will-abort-further-execution-beca
https://stackoverflow.com/questions/57652720/runtimeerror-click-will-abort-further-execution-because-python-3-was-configured
https://forum.qiime2.org/t/runtimeerror-click-will-abort-further-execution-because-python-3-was-configured-to-use-ascii-as-encoding-for-the-environment/7460

I have tried to use `Locale` module in python to solve this 
`locale.setlocale`
https://docs.python.org/3/library/locale.html

but it didn't work either, so from what i see that while initiating python3 it check the locale then it will be too late to change it as click package will crash
