### ISSUE TITLE
shouldn't set SMTP port in the chat flows with quotes 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2942]
### Description

we shouldn't set the SMTP port in our chat flow with double quotes but instead, we should use it as int

**Comment by sameh-farouk** [comment]
i suggest that we can use --set-string in [install_chart](https://github.com/threefoldtech/js-sdk/blob/224f02efcc5e37e4dfee70636900bf20e1e86c8d/jumpscale/sals/kubernetes/manager.py#L100)
because Helm will cast certain values to integers (e.g. true) and also we need certain fields to be always strings like in env vars.

in the case of this issue, the SMTP port when passed with --set will cast to an integer and causes an error.
but Using ```--set-string``` everything should works as expected.

**Comment by RafyAmgadBenjamin** [comment]
The other approach is to update the development file in the chart and make it accept the SMTP port and parse it to string 
`name: {{ .Values.MyName | quote }}`, this approach simpler in implementation but we may face this issue again in another chart, so if we want to use a generic solution that can work for all charts I will go for @sameh-farouk  suggestion, if we want a simple solution, I will go for updating the chart

**Comment by RafyAmgadBenjamin** [comment]
#### fixed
#### Branch
`development_chatflow_envvars`
#### PR
https://github.com/threefoldtech/js-sdk/pull/2966

**Comment by sameh-farouk** [comment]
closes this issue as it was fixed #2966 and verified.
