### ISSUE TITLE
VDC: Create backup with the same name raise error 500

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#3104]
### Description

Create a backup with the same name raise error in the console log and return 500

### Steps to reproduce

1. Create a backup with any name (ex: mybackup)
2. Create another backup with the same name

### Suggested Solution
Check if the name is valid before confirm

**Comment by sameh-farouk** [comment]
verifying this...

**Comment by sameh-farouk** [comment]
@MElborolossy I think hardening is needed.
we should verify if the backup name has only allowed characters for identifiers.
these chars below currently are accepted but still will cause 500 error 
~/\?@!_[A-Z]
so let's assume that the backup name is vailed if contains only small letter and numbers [[a-z], [0-9]),] instead of checking against the space char only in 

https://github.com/threefoldtech/js-sdk/blob/223c05b7230bdac07210a63e1971272874ba291e/jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue#L102
