### ISSUE TITLE
VDC: investigate recovering/redeploying VDC master

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3126]
if the master node dies 
- we lose the embedded etcd of rancher
- the workers are already configured against the old master (using its private network IP)

- my suggestion would be deploy a new master on the same old private network IP and manually reset the workers state and redeploy the IP again on the master, and initiate the velero restore job again

**Comment by AhmedHanafy725** [comment]
### IP Issue
the public IP is attached to the master VM, and if this master went done, we can't guarantee that the same IP will be attached to the new master. https://github.com/threefoldtech/tfexplorer/issues/318

### Storage Issue
Currently there is NO guarantee for restoring the solutions data.
#### solutions
1- Use NFS volumes, but it's not supported on current k3s vms.
2- Use Glusterfs volumes, but it needs at least a cluster with 3 nodes.
3- Create a storage solutions on the grid, so it can be used with kubernetes volumes (IMHO it's the best solution as if the whole cluster is gone, the data will be stored)
4- Use quantum storage as hostpath for volumes, but I think it's not recommended for heavy write/delete solutions.

### Solutions Issue
1- Restore solution with velero, this will reschedule all solutions, but the old one will be removed.
2- Deploy external etcd cluster, so it can be used as kubernetes back-end, but the problem is the minimum requirement for etcd cluster. https://github.com/threefoldtech/js-sdk/issues/2729
