### ISSUE TITLE
Certbot cronjob not installed after moving certbot from apt to pip

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#3171]
Certbot cronjob not installed after moving certbot from apt to pip
Cronjob file path: `/etc/cron.d/certbot`
Cronjob file content:
```
# /etc/cron.d/certbot: crontab entries for the certbot package
#
# Upstream recommends attempting renewal twice a day
#
# Eventually, this will be an opportunity to validate certificates
# haven't been revoked, etc.  Renewal will only occur if expiration
# is within 30 days.
#
# Important Note!  This cronjob will NOT be executed if you are
# running systemd as your init system.  If you are running systemd,
# the cronjob.timer function takes precedence over this cronjob.  For
# more details, see the systemd.timer manpage, or use systemctl show
# certbot.timer.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew
```

**Comment by abom** [comment]
This cron job only runs `certbot renew`, and because threebot can run certbot to:

* Fetch and install the certificate by doing `certbot run`
* Or only install the certificate [if cert paths are set](https://github.com/threefoldtech/js-sdk/blob/8354b5afb118a29943ebe1fa0122d3dcf7ac844e/jumpscale/sals/nginx/nginx.py#L319) by doing `certbot install`

In the second case, certbot won't manage this certificate and doing `certbot certificates` won't list it, hence `certbot renew` won't renew it.

IMO, we add a job for a script which ensures certbot manages this certificate, otherwise, it should run `certbot run` to fetch a new one that can be renewed later.
