### ISSUE TITLE
VDC: support VMs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3215]
part of https://github.com/threefoldtech/home/issues/1091

as a user I'd like from my VDC dashboard to provision a VM

**Comment by waleedhammam** [comment]
**Suggestion**

- Add virtual machine pane in in vdc settings

![Screenshot from 2021-06-27 11-56-42](https://user-images.githubusercontent.com/10658229/123540388-fc8d6080-d73e-11eb-8b60-a15e231d88f8.png)

- Actions will be:
  - delete
  - more information

- Add button will open a chatflow and walk us through vm creation.
  - choose farm (default (auto), the deployed vdc main farm)
  - choose node (optional)
  - public ip or not (default no)
  - choose flist
  - env variables (optional)
  - expose (optional), via domain or gateway
  - deployment (pool, network, public ip(optional), container, subdomain (optional))
  - finishing

**Payment**

- Will be just like add kubernetes worker, if there are extra enough funds in the prepaid wallet it can use it otherwise it will ask user for money.

**Extension and expiration**

- suggestion1: It can deploy within the vdc lifetime, if it expires, the vm expires with it
- suggestion2: can be seperate and runs on it's own, vdc dashboard only manages it

**Comment by waleedhammam** [comment]
**Current limitations**

- Only Ubuntu virtual machine is available 

example deployment

```
vm = zos.vm.create('qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3', network_name='omar', ip_address='172.20.0.15', ssh_keys=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMHTZH
kFbDHyTI23WBTwLKZJd9IqFUsJdNBZILm2GHNYqVNX1hZGy29eZy3tEBtVMJmSORm1SGj35ZAHC/imKQ4ItrXPdQovRihZQMXH45uLWbt2pgF3nK+GoeXjFYlNCD4ujjZrYMkPL1VcbnlrpzdAcx6oz0xPSJHRUPSdolMYl0G0d6nDOUcX4x0fLkzT0crlTNVu2JbQyieU9pbXa1H1iIbNYAN8ELMCHd61NKFH1Hf5nH4Op0irbvk7GhMj673Q97fbXqOomDgFfmL65thInEfcr+9ghZectPwlUzSEJ1JeCIKVa4DDXigbRLP2IaACL68ZTwzbwEUMM14gBimr2IbQ8IBi7vjcSfR3NTkyHS2GYZwP5B7KFYlNnlxlcp0D3is+Gn9X4GN+YjYZqvnnWTJ1eReMOU7fh218LLMcCECCsFUqZULpozoZr+0ZQURMUQNGCrWHqhnbV3u8tqTV8jbxZiLtIGQTLOTp5dO+/dN7je2tR9rdpI5/J/8= omar@omar-Inspiron-5520', 'khaledadsf'], pool_id=12
9, name='Ubuntu-20.04', size=6, public_ip_wid=0)
```

- name `Ubuntu-20.04` shouldn't be changed

- only one vm can be deployed on a network (without k8s for sure) on the same node

**Comment by xmonader** [comment]
- I don't think we can have environment variables in the VMs yet
- Indeed it's ubuntu VMs for now so let's make sure we communicate that to the user in the chatflow
- I suggest the expose flow to be completely independent of the VMs creation too

**Comment by waleedhammam** [comment]
@xmonader yeah noted, currently making some experiments and deployments to the vm

**Comment by waleedhammam** [comment]
Couldn't deploy vms due to these errors: https://github.com/threefoldtech/js-sdk/issues/3221
