### ISSUE TITLE
cryptpad.fr solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#419]
- https://cryptpad.fr/
- https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide

- [x] flist
- [x] admin solution
- [x] marketplace solution

**Comment by BolaNasr** [comment]
We deployed it in http://138.68.66.25:3000 
but we have problem that's direct us to new approach :
- CryptPad stores each document in an individual file on your hard drive in container that run server.
- if container gone everything is gone too .
- so we need to make backup approach to backup your data in other server to can get it again if container gone or that's problem of user if container gone because he didn't extend his pool.

**Comment by BolaNasr** [comment]
Flist: https://hub.grid.tf/bola.3bot/3bot-cryptopad-latest.flist 

TODO : 
- Test flist ( stellar now is down)
- domain expose

**Comment by BolaNasr** [comment]
Docker file : https://github.com/threefoldtech/tf-images/tree/master/cryptpad
Flist: https://github.com/threefoldtech/tf-images/tree/master/cryptpad
Chatflows **Done**
Solution Expose **Done**

![photo_2020-08-10_11-30-03](https://user-images.githubusercontent.com/10259267/89804344-5c354a00-db34-11ea-9e59-b99220e95603.jpg)
![photo_2020-08-10_11-31-08](https://user-images.githubusercontent.com/10259267/89804355-5e97a400-db34-11ea-8dc5-bfa6a5551fbe.jpg)

TODO: **https**

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-25 16-28-44](https://user-images.githubusercontent.com/26298009/91186856-cda5f880-e6ef-11ea-8da3-7fb5dfe7d9af.png)

![Screenshot from 2020-08-25 16-29-31](https://user-images.githubusercontent.com/26298009/91186862-cf6fbc00-e6ef-11ea-823a-291ef7f0ca2a.png)

![Screenshot from 2020-08-25 16-32-53](https://user-images.githubusercontent.com/26298009/91187157-22e20a00-e6f0-11ea-96f4-478ac8ed0b7d.png)
