### ISSUE TITLE
Change how we display the solutions in the dashboard

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#434]
I suggest that the solutions to be grouped and displayed like this to handle the large number of solutions that we are going to do.

This for listing
![image](https://user-images.githubusercontent.com/46320202/89735392-84547880-da62-11ea-8488-7aee4694c9c8.png)

This for the sub items
![image](https://user-images.githubusercontent.com/46320202/89735393-874f6900-da62-11ea-8b68-3eaf18f467cf.png)

**Comment by AhmedSa-mir** [comment]
![Screenshot from 2020-08-19 18-01-04](https://user-images.githubusercontent.com/18093386/90660327-10765500-e246-11ea-8d15-ee6420300d18.png)

![Screenshot from 2020-08-19 18-01-28](https://user-images.githubusercontent.com/18093386/90660329-12401880-e246-11ea-877d-c89a41244b5f.png)

All functionalities are working (New and view workloads).
TODO: Change icons to images because icons are small and don't fit well.

**Comment by Dina-Abd-Elrahman** [comment]
**commit_ID** 156d43d7f65397a02d69b6158041625f2230b3fa , **Branch** development_capacitypool_apps

![ff](https://user-images.githubusercontent.com/21218053/91039589-1d5fc380-e60d-11ea-8c51-831a473e38d6.png)

![ff1](https://user-images.githubusercontent.com/21218053/91039643-37010b00-e60d-11ea-8ba5-35c3a858639d.png)
