### ISSUE TITLE
Error while trying to install packages from the dashboard 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#581]
- I got an error in jsng shell while trying to install packages from the dashboard, but it's added correctly and listed 
``` j.servers.threebot.default.packages.list_all() ```

** Commit_ID** 45faa13faac137431eb634cc8d73553a5d125cc6 , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91045333-058d3d00-e617-11ea-9fbb-a8290099dfd8.png)

![ff1](https://user-images.githubusercontent.com/21218053/91045364-0e7e0e80-e617-11ea-80a1-2a871d8b2b98.png)

![ff2](https://user-images.githubusercontent.com/21218053/91045381-150c8600-e617-11ea-9623-d949830443de.png)

**Comment by AhmedSa-mir** [comment]
Tested all packages installation and deletion from UI:
- All is working but these packages [`polls`, `marketplace` `stellar_stats`] raise an error like the one above in the shell during installation. This error is related to the certificate generation because we are working on localhost without domain, so it should be just happening while working on localhost.
- Package kyc raises an error on frontend during installation but afterthat it's added in the packages list, so I opened https://github.com/threefoldtech/js-sdk/issues/645 to track this one.
