### ISSUE TITLE
3BOT ADMIN: POOL - screen #4 should be removed. why should users choose which wallet they wanna use?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#907]
<img width="848" alt="Screenshot 2020-09-02 at 16 30 33" src="https://user-images.githubusercontent.com/43240801/91998886-14bd6a80-ed3c-11ea-9f72-f8414134b58f.png">

not everyone has a testnet / staging 3bot wallet app.

we dont even have a manual on howe to get a staging 3bot wallet.

at the moment people pay with solar wallet or interstellar wallet testnet... 

can we delete this page altogether?  its a repetition for the following page. #906

**Comment by xmonader** [comment]
This page won't be removed

3Bot user is allowed to choose a wallet they created on their system for payments. In my case, I've a few wallets available on my 3Bot, And **typically** people will _create a 3Bot,_ _create a wallet_ on that 3Bot, _wire money to that wallet_ and use it in their payments.

![image](https://user-images.githubusercontent.com/64129/92031892-9d063480-ed69-11ea-8dba-471e76742c12.png)


> not everyone has a testnet / staging 3bot wallet app.

That's not a reason, the only reason to remove payments with 3Bot connect app is "dropping the 3Bot connect as a wallet"
This system is going live, against mainnet, and not because the testers don't have a testnet app (or don't know about it) we remove a main feature for payments using the 3Bot connect wallet. *This is this foundation main wallet* please feel free to reach out to jimber team to provide you with that information if needed or ask them to document their system.

**Comment by despiegk** [comment]
ofcourse the internal wallets are important
it shouldn't be called 3bot app: I suggest call it "External Wallet (QR Code)" because it can be any wallet

**Comment by xmonader** [comment]
@despiegk I applied your suggestion

![image](https://user-images.githubusercontent.com/64129/92071886-31938580-edb0-11ea-88ce-0f25f85100ca.png)
